Implemented JMX management and monitoring of the nodes Added corresponding features in the administration console Fixed a bug that would cause the nodes to crash on a NoClassDefFoundError or ClassNotFoundExceptrion Fixed an issue in nodes security policy causing the JMX server to crash Fixed an issue preventing the driver from detecting that a node was disconnected